# Generated by Django 5.1.7 on 2025-03-25 18:15

import autoslug.fields
import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50, null=True)),
                ('slug', autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='category', unique=True)),
                ('logo', models.CharField(max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, null=True)),
                ('description', django_ckeditor_5.fields.CKEditor5Field()),
                ('website', models.CharField(blank=True, max_length=50, null=True)),
                ('position', models.CharField(max_length=100)),
                ('slug', autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='position', unique=True)),
                ('min_salary', models.IntegerField()),
                ('max_salary', models.IntegerField()),
                ('yearly_salary', models.IntegerField()),
                ('post_date', models.DateField(auto_now_add=True, null=True)),
                ('post_time', models.TimeField(auto_now_add=True, null=True)),
                ('apply_date', models.DateField(null=True)),
                ('apply_time', models.TimeField(null=True)),
                ('vacancy', models.IntegerField(null=True)),
                ('required_knowledge', django_ckeditor_5.fields.CKEditor5Field(null=True)),
                ('required_experience', django_ckeditor_5.fields.CKEditor5Field(null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jobapp.category')),
                ('company_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobapp.recuiter')),
                ('job_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jobapp.type')),
            ],
        ),
        migrations.CreateModel(
            name='Job_Apply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_letter', models.TextField(null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('applicants', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jobapp.applicant')),
                ('job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jobapp.job')),
                ('recruiter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobapp.recuiter')),
            ],
        ),
    ]
