# Generated by Django 4.2.20 on 2025-03-26 16:50

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0002_category_type_job_job_apply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='required_experience',
        ),
        migrations.RemoveField(
            model_name='job',
            name='required_knowledge',
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='category', unique=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='position', unique=True),
        ),
    ]
