# Generated by Django 4.2.20 on 2025-03-26 16:50

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0003_remove_job_required_experience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='qualification',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='responsibility',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
        ),
    ]
