# Generated by Django 4.2.20 on 2025-03-26 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0004_job_qualification_job_responsibility'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='yearly_salary',
        ),
    ]
