# Generated by Django 4.2.20 on 2025-03-27 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0005_remove_job_yearly_salary'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Job_Apply',
        ),
    ]
