# Generated by Django 4.2.20 on 2025-03-27 17:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0006_delete_job_apply'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job_Apply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_letter', models.TextField(null=True)),
                ('cv', models.FileField(upload_to='resume', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('portfolio', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('applicants', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jobapp.applicant')),
                ('job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jobapp.job')),
                ('recruiter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobapp.recuiter')),
            ],
        ),
    ]
