from django.urls import path
from . import views
urlpatterns = [
    path('', views.index, name='index'),
    path('author', views.author, name='author'),
    path('register', views.register, name='register'),
    path('login', views.logins, name='login'),
    path('email-login', views.email_login, name='email_login'),
    path('send-otp', views.send_otp, name='send_otp'),
    path('verify-otp', views.verify_otp_view, name='verify_otp'),
    path('resend-otp', views.resend_otp, name='resend_otp'),
    path('do_login', views.do_login, name='do_login'),
    path('do_logout', views.dologout, name='dologout'),
    path('check_registration', views.check_registration, name='check_registration'),
    path('about', views.about, name='about'),
    path('contact', views.contact, name='contact'),
    path('recruiter/job_apply', views.job_apply, name='job_apply'),
    path('recruiter/add_job', views.add_job, name='add_job'),
    path('get_job/<slug>', views.get_job, name='get_job'),
    path('search_job', views.searching, name='search_job'),
    path('search_result', views.search_result, name='search_result'),
    path('job_details/<slug>', views.job_details, name='job_details'),
    path('job/apply/<slug:slug>', views.job_application, name='job_application'),
    path('profile/my_profile', views.my_profile, name='my_profile'),
    path('profile/edit_profile', views.edit_profile, name='edit_profile'),
    path('profile/edited_profile', views.edited_profile, name='edited_profile'),
    path('job/history', views.application_history, name='application_history'),
    path('profile/cng_pass', views.cng_pass, name='cng_pass'),
    path('profile/password_changed', views.password_changed, name='password_changed'),
    path('recuiter/application_notification', views.application_notification, name='application_notification'),
    path('recruiter/update_status/<int:application_id>', views.update_application_status, name='update_application_status'),
    path('notifications', views.view_notifications, name='view_notifications'),
    path('notifications/mark_read/<int:notification_id>', views.mark_notification_read, name='mark_notification_read'),
    path('privacy-policy', views.privacy_policy, name='privacy_policy'),
    path('terms-conditions', views.terms_conditions, name='terms_conditions'),
    path('our-services', views.our_services, name='our_services'),
    
    # Password reset URLs
    path('forgot-password/', views.forgot_password, name='forgot_password'),
    path('send-reset-email/', views.send_reset_email, name='send_reset_email'),
    path('reset-password/<int:user_id>/<str:token>/', views.reset_password, name='reset_password'),
    path('reset-password-confirm/', views.reset_password_confirm, name='reset_password_confirm'),
]